### ISSUE TITLE
Difficulty with replique/repl command: authentication issue?

### ISSUE THREAD

**Issue by sogaiu** [EwenG/replique.el#9]
Attempting to follow the "Getting Started" instructions, in the midst of M-x replique/repl, after having selected \*default\*, I encountered an authentication error.

I changed the value of replique/replique-coords in replique.el from:

```
"{:git/url \"git@github.com:EwenG/replique.git\" :sha \"7c92459ebffe136e2b0fb1f9cd1e13ba692a20e6\"}"
```

to:

```
"{:git/url \"https://github.com/EwenG/replique.git\" :sha \"7c92459ebffe136e2b0fb1f9cd1e13ba692a20e6\"}"
```

around:

https://github.com/EwenG/replique.el/blob/ccc2f735a2ab770f2e207fdf1680029d967024f0/replique.el#L1085

Trying again after this, resulted in success.

For reference, I encountered a similar situation when trying replique manually as described at replique's README.  An analogous change helped there too.

Is this a problem on my end?

**Comment by EwenG** [comment]
Thanks it's fixed !

**Comment by sogaiu** [comment]
Thanks!
